/** Central configuration. Keep sheet names, headers, aliases, and policy here. */
var APP_CONFIG = Object.freeze({
  appName: '当日情報媒体AI',
  timeZone: 'Asia/Tokyo',
  lockTimeoutMs: 30000,
  sheets: Object.freeze({
    inputs: Object.freeze([
      Object.freeze({ name: '26参参フォーム回答', type: 'FORM', priority: 10 }),
      Object.freeze({
        name: '26運スタ企画フォーム回答',
        type: 'STAFF_FORM',
        priority: 10,
        defaults: Object.freeze({ participation: '運営スタッフ企画' })
      }),
      Object.freeze({
        name: '26運スタ企画その他掲載情報',
        type: 'STAFF_OTHER_PUBLICATION',
        priority: 10,
        syncToMaster: false,
        syncToBureaus: true
      }),
      Object.freeze({
        name: '26参参変更申請',
        type: 'PARTICIPANT_CHANGE',
        priority: 30,
        syncToMaster: false
      }),
      Object.freeze({
        name: '26運スタ企画変更申請',
        type: 'STAFF_CHANGE',
        priority: 30,
        syncToMaster: false
      })
    ]),
    master: '26掲載情報マスター',
    participantOutput: '参参一覧',
    participantExclusions: '26参参除外管理',
    foodOutput: '屋台情報まとめ',
    bureauOutputs: Object.freeze([
      Object.freeze({ bureau: '会場整備局', name: '26会場整備局' }),
      Object.freeze({ bureau: '参加対応局', name: '26参加対応局' }),
      Object.freeze({ bureau: '開発局', name: '26開発局' }),
      Object.freeze({ bureau: '企画局', name: '26企画局' }),
      Object.freeze({ bureau: '広報制作局', name: '26広報制作局' }),
      Object.freeze({ bureau: '渉外局', name: '26渉外局' }),
      Object.freeze({ bureau: '総務局', name: '26総務局' }),
      Object.freeze({ bureau: '財務局', name: '26財務局' }),
      Object.freeze({ bureau: '超局PJ', name: '26超局PJ' })
    ]),
    manualReview: '26要手動確認',
    log: '26処理ログ'
  }),
  properties: Object.freeze({
    environment: 'APP_ENV',
    spreadsheetId: 'EXPECTED_SPREADSHEET_ID',
    releaseId: 'RELEASE_ID',
    scheduledSync: 'ENABLE_SCHEDULED_SYNC'
  }),
  masterHeaders: Object.freeze([
    '管理ID',
    'メールアドレス',
    '参加企画',
    '所属局',
    '団体名',
    '企画名',
    '販売物',
    '画像リンク',
    'データソース',
    '同期ステータス',
    '最終更新日時',
    '要確認',
    '要確認理由'
  ]),
  participantOutputHeaders: Object.freeze([
    '参加企画',
    '提出状況',
    'メールアドレス',
    '参参名・フォーム回答',
    '参参名・確定版',
    '企画名・フォーム回答',
    '企画名・確定版',
    '照合結果',
    '最終同期日時',
    '回答識別子'
  ]),
  previousParticipantTrackerHeadersWithoutResponseId: Object.freeze([
    '参加企画',
    '提出状況',
    'メールアドレス',
    '参参名・フォーム回答',
    '参参名・確定版',
    '企画名・フォーム回答',
    '企画名・確定版',
    '照合結果',
    '最終同期日時'
  ]),
  previousParticipantTrackerHeaders: Object.freeze([
    '参加企画',
    '提出状況',
    'メールアドレス',
    '参参名・参加申し込み時',
    '参参名・フォーム回答',
    '参参名・確定版',
    '企画名・フォーム回答',
    '企画名・確定版',
    '照合結果',
    '最終同期日時'
  ]),
  participantExclusionHeaders: Object.freeze([
    '回答識別子',
    '除外日時',
    '除外理由'
  ]),
  participantDuplicateResult: '同一メアド・参参名・参加企画重複',
  previousParticipantDuplicateResult: '同一メアド・参参名重複',
  participantDuplicateWarningBackground: '#fff2cc',
  previousParticipantOutputHeaders: Object.freeze([
    '管理ID',
    '参加企画',
    '所属局',
    '団体名',
    '企画名',
    '販売物',
    '画像リンク',
    '最終更新日時'
  ]),
  participantAutomaticHeaders: Object.freeze([
    '参参名・フォーム回答',
    '参参名・確定版',
    '企画名・フォーム回答',
    '企画名・確定版',
    '照合結果',
    '最終同期日時',
    '回答識別子'
  ]),
  participantStatusOptions: Object.freeze([
    '提出済み',
    '確認中',
    '未提出',
    'キャンセル'
  ]),
  participantColumnWidths: Object.freeze({
    '参加企画': 210,
    '提出状況': 120,
    'メールアドレス': 190,
    '参参名・フォーム回答': 300,
    '参参名・確定版': 300,
    '企画名・フォーム回答': 300,
    '企画名・確定版': 300,
    '照合結果': 150,
    '最終同期日時': 165
  }),
  foodOutputHeaders: Object.freeze([
    '管理ID',
    '参加企画',
    '所属局',
    '団体名',
    '企画名',
    '販売物',
    '画像リンク',
    '要確認'
  ]),
  bureauAutomaticHeaders: Object.freeze([
    '企画名',
    '企画紹介文',
    '担当者名',
    '部署名',
    '企画場所',
    '企画日時',
    '企画ジャンル',
    '整理券情報',
    'ゲスト情報',
    '備考',
    '変更反映状況',
    '最終変更申請日時'
  ]),
  bureauManualHeaders: Object.freeze([
    '内部向け企画・取り組み名',
    '掲載文字情報',
    'ページ名',
    '掲載媒体',
    '当媒チェック',
    '校閲チェック'
  ]),
  bureauPublicationMediaOptions: Object.freeze([
    'パンフレット',
    'Webサイト',
    'パンフ／Web'
  ]),
  bureauCheckStatusOptions: Object.freeze([
    '未確認',
    '確認中',
    '確認済み',
    '修正必要'
  ]),
  bureauOtherPublicationSourceType: 'STAFF_OTHER_PUBLICATION',
  bureauOtherPublicationSectionLabel: 'その他掲載情報',
  bureauOtherPublicationSectionBackground: '#5b73b7',
  bureauFrozenThroughHeader: '掲載媒体',
  bureauColumnWidths: Object.freeze({
    'ページ名': 170,
    '内部向け企画・取り組み名': 175,
    '企画名': 170,
    '掲載文字情報': 120,
    '担当者名': 90,
    '部署名': 110,
    '掲載媒体': 125,
    '当媒チェック': 100,
    '校閲チェック': 100,
    '変更反映状況': 120,
    '企画日時': 100,
    '企画場所': 120,
    '企画紹介文': 260,
    '企画ジャンル': 120,
    '整理券情報': 200,
    'ゲスト情報': 200,
    '備考': 200,
    '最終変更申請日時': 150
  }),
  bureauOutputHeaders: Object.freeze([
    'ページ名',
    '内部向け企画・取り組み名',
    '企画名',
    '掲載文字情報',
    '担当者名',
    '部署名',
    '掲載媒体',
    '当媒チェック',
    '校閲チェック',
    '変更反映状況',
    '企画日時',
    '企画場所',
    '企画紹介文',
    '企画ジャンル',
    '整理券情報',
    'ゲスト情報',
    '備考',
    '最終変更申請日時'
  ]),
  previousBureauOutputHeaders: Object.freeze([
    '企画名',
    '企画紹介文',
    '担当者名',
    '部署名',
    '企画場所',
    '企画日時',
    '企画ジャンル',
    '整理券情報',
    'ゲスト情報',
    '備考',
    '変更反映状況',
    '最終変更申請日時'
  ]),
  legacyBureauOutputHeaders: Object.freeze([
    '受付種別',
    '回答日時',
    '所属局',
    '部署名',
    '企画名',
    '担当者名',
    '企画紹介文',
    '企画場所',
    '11月7日開始',
    '11月7日終了',
    '11月8日開始',
    '11月8日終了',
    'その他企画日時',
    '企画ジャンル',
    '企画ジャンル（メイン）',
    '整理券配布',
    '整理券配布詳細',
    'ゲスト',
    'ゲスト名',
    'ゲスト名 フリガナ',
    'ゲスト肩書き',
    'ゲスト名の公表',
    '変更前',
    '変更前画像',
    '変更後',
    '変更後画像',
    '備考',
    '入力タブ',
    '入力行'
  ]),
  manualReviewHeaders: Object.freeze([
    '確認キー',
    '受付日時',
    '所属局',
    '部署名',
    '企画名',
    '担当者名',
    '要確認理由',
    '変更前',
    '変更後',
    '変更前画像',
    '変更後画像',
    '入力タブ',
    '入力行',
    '対応状況'
  ]),
  logHeaders: Object.freeze([
    '実行ID',
    '記録日時',
    '環境',
    '処理',
    'レベル',
    'エラーコード',
    '入力タブ',
    '行番号',
    '列名',
    '説明',
    '新規件数',
    '更新件数',
    'スキップ件数',
    '要確認件数',
    'リリースID'
  ]),
  inputHeaderCandidates: Object.freeze({
    officialId: Object.freeze(['企画ID', '正式企画ID', '管理ID', '企画番号']),
    email: Object.freeze(['メールアドレス', 'メール', 'Email', 'E-mailアドレス']),
    participation: Object.freeze(['参加企画', '参加形態', '企画区分', '部門']),
    bureau: Object.freeze(['所属局']),
    organization: Object.freeze([
      '団体名',
      '参加団体名',
      'サークル名',
      '参加団体・参加者名（17字以内推奨・36字以内）',
      '部署名（チーム、PJなど）',
      '部署名'
    ]),
    projectName: Object.freeze([
      '変更後企画名',
      '企画名',
      '掲載企画名',
      '催事名',
      '企画名（26字以内）',
      '企画名（24字以内）'
    ]),
    salesItems: Object.freeze([
      '変更後販売物',
      '販売物',
      '販売品目',
      '販売内容',
      '飲食物',
      '販売物について'
    ]),
    imageLink: Object.freeze([
      '変更後画像リンク',
      '画像リンク',
      '画像URL',
      '画像',
      '掲載画像',
      'サムネイル画像提出',
      '画像提出（飲食サムネイル画像）',
      'アイコン画像提出',
      '画像提出（飲食アイコン画像）'
    ]),
    timestamp: Object.freeze(['タイムスタンプ', '回答日時', '申請日時', '送信日時'])
  }),
  bureauViewHeaderCandidates: Object.freeze({
    timestamp: Object.freeze(['タイムスタンプ', '回答日時', '申請日時', '送信日時']),
    bureau: Object.freeze(['所属局']),
    department: Object.freeze(['部署名（チーム、PJなど）', '部署名']),
    projectName: Object.freeze(['企画名（26字以内）', '企画名']),
    staffName: Object.freeze(['担当者名']),
    introduction: Object.freeze(['企画紹介文（75字以内）']),
    publicationText: Object.freeze(['掲載文字情報']),
    place: Object.freeze(['企画場所（正式名称）']),
    firstDayStart: Object.freeze(['11月7日(土)企画開始時間']),
    firstDayEnd: Object.freeze(['11月7日(土)企画終了時間']),
    secondDayStart: Object.freeze(['11月8日(日)企画開始時間']),
    secondDayEnd: Object.freeze(['11月8日(日)企画終了時間']),
    otherSchedule: Object.freeze(['当日企画でない場合は、企画日時を詳細に記入してください。']),
    genres: Object.freeze(['企画ジャンル']),
    mainGenre: Object.freeze(['企画ジャンル(メイン)', '企画ジャンル（メイン）']),
    ticketDistribution: Object.freeze(['整理券（無料チケット）配布']),
    ticketDetails: Object.freeze(['整理券配布詳細']),
    guest: Object.freeze(['ゲスト']),
    guestName: Object.freeze(['ゲスト名']),
    guestKana: Object.freeze(['ゲスト名 フリガナ']),
    guestTitle: Object.freeze(['ゲスト肩書き']),
    guestPublication: Object.freeze(['ゲスト名の公表']),
    beforeChange: Object.freeze(['変更前']),
    beforeImage: Object.freeze(['変更前（画像の場合はこちらに提出してください）']),
    afterChange: Object.freeze(['変更後']),
    afterImage: Object.freeze(['変更後（画像の場合はこちらに提出してください）']),
    notes: Object.freeze(['備考'])
  }),
  requiredBureauOtherPublicationFields: Object.freeze([
    'timestamp',
    'bureau',
    'department',
    'projectName',
    'staffName'
  ]),
  staffChangeFields: Object.freeze([
    Object.freeze({ field: 'projectName', labels: Object.freeze(['企画名', '外部向け企画・取り組み名']) }),
    Object.freeze({ field: 'introduction', labels: Object.freeze(['企画紹介文', '企画紹介文（75字以内）']) }),
    Object.freeze({ field: 'staffName', labels: Object.freeze(['担当者名', '責任者名']) }),
    Object.freeze({ field: 'bureau', labels: Object.freeze(['所属局']) }),
    Object.freeze({ field: 'department', labels: Object.freeze(['部署名', '部署名（チーム、PJなど）', 'チーム・班']) }),
    Object.freeze({ field: 'place', labels: Object.freeze(['企画場所', '企画場所（正式名称）']) }),
    Object.freeze({ field: 'scheduleOverride', labels: Object.freeze(['企画時間', '企画日時', '企画実施日']) }),
    Object.freeze({ field: 'firstDayStart', labels: Object.freeze(['11月7日(土)企画開始時間']) }),
    Object.freeze({ field: 'firstDayEnd', labels: Object.freeze(['11月7日(土)企画終了時間']) }),
    Object.freeze({ field: 'secondDayStart', labels: Object.freeze(['11月8日(日)企画開始時間']) }),
    Object.freeze({ field: 'secondDayEnd', labels: Object.freeze(['11月8日(日)企画終了時間']) }),
    Object.freeze({ field: 'otherSchedule', labels: Object.freeze(['その他企画日時', '当日企画でない場合は、企画日時を詳細に記入してください。']) }),
    Object.freeze({ field: 'genres', labels: Object.freeze(['企画ジャンル']) }),
    Object.freeze({ field: 'mainGenre', labels: Object.freeze(['企画ジャンル(メイン)', '企画ジャンル（メイン）']) }),
    Object.freeze({ field: 'ticketDistribution', labels: Object.freeze(['整理券配布', '整理券（無料チケット）配布']) }),
    Object.freeze({ field: 'ticketDetails', labels: Object.freeze(['整理券配布詳細']) }),
    Object.freeze({ field: 'guest', labels: Object.freeze(['ゲスト']) }),
    Object.freeze({ field: 'guestName', labels: Object.freeze(['ゲスト名']) }),
    Object.freeze({ field: 'guestKana', labels: Object.freeze(['ゲスト名 フリガナ']) }),
    Object.freeze({ field: 'guestTitle', labels: Object.freeze(['ゲスト肩書き']) }),
    Object.freeze({ field: 'guestPublication', labels: Object.freeze(['ゲスト名の公表']) }),
    Object.freeze({ field: 'notes', labels: Object.freeze(['備考']) })
  ]),
  requiredInputFields: Object.freeze([
    'email',
    'participation',
    'organization',
    'projectName'
  ]),
  foodRule: Object.freeze({
    exactParticipationValues: Object.freeze([
      '飲食物販売企画',
      '飲食販売企画',
      '模擬店',
      '屋台'
    ]),
    participationKeywords: Object.freeze(['飲食', '食品', '模擬店', '屋台']),
    requireSalesItem: true
  }),
  provisionalIdPrefix: 'TMP-',
  triggerHandlers: Object.freeze(['handleFormSubmit_', 'scheduledSyncMaster_'])
});
